# Generated by Django 4.2.16 on 2025-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='nombre del proyecto')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='url del sitio')),
                ('repository_url', models.URLField(blank=True, null=True, verbose_name='url del repositorio')),
                ('description', models.TextField(verbose_name='descripción del proyecto')),
                ('image', models.ImageField(blank=True, upload_to='projects_images', verbose_name='imagen del proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
            },
        ),
    ]
