# Generated by Django 4.2.16 on 2025-02-28 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=256, verbose_name='profesión')),
                ('skills', models.CharField(max_length=256, verbose_name='habilidades')),
                ('about_me', models.TextField(verbose_name='acerca de mi')),
                ('image', models.ImageField(blank=True, upload_to='user_images', verbose_name='imagen del usuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil del usuario',
            },
        ),
    ]
